// ===== GROUP TYPES =====
export interface GroupNeeds {
  major: "SE" | "SS";
  count: number;
}

export interface GroupMember {
  userId: string;
  fullName: string;
  avatarUrl?: string;
  role?: "leader" | "member";
  major?: "SE" | "SS";
  username?: string;
  email?: string;
  roleInGroup?: string;
}

export interface Group {
  groupId: string;
  id?: string;
  groupName: string;
  name?: string;
  topicName?: string | null;
  courseId: string;
  courseCode: string;
  courseName?: string;
  memberCount: number;
  maxMembers: number;
  leaderName: string;
  leaderId: string;
  status: "open" | "lock" | "finalize" | "private";
  majors: ("SE" | "SS")[];
  createdDate: string;
  members: GroupMember[];
  needs: GroupNeeds[];
  isLockedByRule?: boolean;
  approvalStatus?: "pending" | "approved" | "rejected";
  rejectionReason?: string;
  approvalDate?: string;
  approvedBy?: string;
  autoGenerated?: boolean;
  ready?: boolean;
  isReady?: boolean; // true = Ready, false = NotReady
}

export interface GroupDetail extends Group {
  skills: string[];
  groupRoles: GroupRole[];
}

export interface GroupRole {
  userId: string;
  role: "leader" | "member" | "secretary" | "treasurer";
  assignedDate: string;
}

export interface GroupApprovalAction {
  groupId: string;
  action: "approve" | "reject";
  reason?: string;
  approvedBy: string;
  approvalDate: string;
}

export interface MemberChangeAction {
  groupId: string;
  studentId: string;
  reason: string;
  changedBy: string;
  changedAt: string;
}

export interface ProposeAdjustmentPayload {
  groupId: string;
  proposal: string;
  proposedBy: string;
  proposedAt: string;
}

export interface CreateGroupForm {
  groupName: string;
  courseId: string;
  description?: string;
}

export type GroupStatus = "active" | "inactive";
export type GroupRoleName = "leader" | "member" | "secretary";
